# Generated by Django 4.2.9 on 2026-04-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_leave_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='certificate_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='certificate_verified',
            field=models.BooleanField(default=False),
        ),
    ]
