# Generated by Django 4.2.9 on 2026-04-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_leave_certificate_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
