# Generated by Django 4.2.9 on 2026-07-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_leave_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='advisor_approved',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], db_index=True, default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='leave',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='final_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], db_index=True, default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='leave',
            name='hod_approved',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], db_index=True, default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='leave',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='leave',
            name='tutor_approved',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], db_index=True, default='Pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['student', 'date'], name='leave_leave_student_2c500e_idx'),
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['student', 'leave_type', 'final_status'], name='leave_leave_student_c829ac_idx'),
        ),
    ]
