# Generated by Django 5.2.12 on 2026-04-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_age_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Tutor', 'Tutor'), ('Advisor', 'Advisor')], default='Normal', max_length=20),
        ),
    ]
