# Generated by Django 5.2.12 on 2026-04-09 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_staff_staff_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='advisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['staff', 'hod']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='tutor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['staff', 'hod']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutored_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
