# Generated by Django 4.2.9 on 2026-06-25 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_subject_student_class_alter_subject_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['reg_no', 'user__username']},
        ),
    ]
