# Generated by Django 4.2.9 on 2026-07-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_student_reg_no_alter_student_roll_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_type',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('OPEN_ELECTIVE', 'Open Elective')], default='REGULAR', max_length=20),
        ),
        migrations.AddField(
            model_name='class',
            name='elective_students',
            field=models.ManyToManyField(blank=True, related_name='elective_classes', to='accounts.student'),
        ),
    ]
