# Generated by Django 4.2.9 on 2026-07-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_class_class_type_class_elective_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('OPEN_ELECTIVE', 'Open Elective')], default='REGULAR', max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
