# Generated by Django 5.2.12 on 2026-07-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_subject_semester_subject_subject_type_subject_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_type',
            field=models.CharField(choices=[('REGULAR', 'Regular')], default='REGULAR', max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('REGULAR', 'Regular')], default='REGULAR', max_length=20),
        ),
    ]
