# Generated by Django 4.2.9 on 2026-07-29 04:35

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_class_class_type_alter_subject_subject_type'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='elective_students',
            field=models.ManyToManyField(blank=True, related_name='elective_subjects', to='accounts.student'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('OPEN_ELECTIVE', 'Open Elective')], default='REGULAR', max_length=20),
        ),
    ]
