# Generated by Django 4.2.9 on 2026-07-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_managers_subject_elective_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='accepted_classes',
            field=models.ManyToManyField(blank=True, related_name='accepted_open_electives', to='accounts.class'),
        ),
    ]
