# Generated by Django 5.2.12 on 2026-07-31 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_subject_subject_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='rejected_classes',
            field=models.ManyToManyField(blank=True, related_name='rejected_open_electives', to='accounts.class'),
        ),
    ]
