# Generated by Django 4.2.9 on 2026-08-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_subject_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='batch',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('THEORY', 'Theory'), ('THEORY_CUM_PRACTICAL', 'Theory Cum Practical'), ('PROFESSIONAL_ELECTIVE', 'Professional Elective'), ('OPEN_ELECTIVE', 'Open Elective'), ('REGULAR', 'Regular (Theory)')], default='THEORY', max_length=30),
        ),
    ]
