# Generated by Django 4.2.9 on 2026-08-22 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_class_batch_alter_subject_subject_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('THEORY', 'Theory'), ('PRACTICAL', 'Practical / Lab'), ('THEORY_CUM_PRACTICAL', 'Theory Cum Practical'), ('PROFESSIONAL_ELECTIVE', 'Professional Elective'), ('OPEN_ELECTIVE', 'Open Elective'), ('REGULAR', 'Regular (Theory)')], default='THEORY', max_length=30),
        ),
    ]
