# Generated by Django 4.2.9 on 2026-07-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='period',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['student_class', 'day', 'period'], name='timetable_s_student_1da620_idx'),
        ),
    ]
