# Generated by Django 4.2.9 on 2026-04-14 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='staff_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='staff_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
