# Generated by Django 4.2.9 on 2026-06-16 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0002_otp_staff_latitude_otp_staff_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_otps', to=settings.AUTH_USER_MODEL),
        ),
    ]
