# Generated by Django 5.2.12 on 2026-07-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_periodlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='staff_accuracy',
            field=models.FloatField(blank=True, default=10.0, null=True),
        ),
    ]
