# Generated by Django 5.2.12 on 2026-08-09 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_class_batch_alter_subject_subject_type'),
        ('attendance', '0006_alter_attendance_date_alter_attendance_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='periodlock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='periodlock',
            name='note',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='periodlock',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.subject'),
        ),
        migrations.AddIndex(
            model_name='periodlock',
            index=models.Index(fields=['student_class', 'subject', 'date'], name='attendance__student_cf2704_idx'),
        ),
    ]
