# Generated by Django 4.2.9 on 2026-08-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_subject_subject_type'),
        ('attendance', '0007_periodlock_created_at_periodlock_note_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='periodlock',
            name='attendance__student_cf2704_idx',
        ),
        migrations.AlterUniqueTogether(
            name='periodlock',
            unique_together={('student_class', 'subject', 'date', 'period')},
        ),
        migrations.AddIndex(
            model_name='periodlock',
            index=models.Index(fields=['student_class', 'subject', 'date', 'period'], name='attendance__student_79ede3_idx'),
        ),
    ]
